[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/como-comprar-por-alibaba/"
  to = "https://blog.andreioctaviandanciulescu.com/como-comprar-por-alibaba"
  status = 301
  force = true

[[redirects]]
  from = "/como-hacer-tu-tfg-con-inteligencia-artificial/"
  to = "https://blog.andreioctaviandanciulescu.com/como-hacer-tu-tfg-con-inteligencia-artificial"
  status = 301
  force = true

[[redirects]]
  from = "/desafios-triunfos-starbucks-howard-schultz/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/aiprm-para-chatgpt/"
  to = "https://blog.andreioctaviandanciulescu.com/aiprm-para-chatgpt"
  status = 301
  force = true

[[redirects]]
  from = "/consejos-brian-tracy-gestion-tiempo/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/analisis-arte-amar-fromm/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/algoritmos-para-la-vida-cotidiana/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/que-es-una-llc-y-como-crearla/"
  to = "https://blog.andreioctaviandanciulescu.com/como-crear-una-llc"
  status = 301
  force = true

[[redirects]]
  from = "/lider-exitoso-john-maxwell/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/caso-brunswick/"
  to = "/"
  status = 301
  force = true